### ISSUE TITLE
Testare back end

### ISSUE THREAD

**Issue by GabrielMajeri** [ToniBiro/Interseco#16]
Avem deja câteva teste pentru partea de algoritm scrise în [pytest](https://docs.pytest.org/en/latest/). Ar trebui să le extindem să acopere mai multe cazuri exceptate.

De asemenea, ar ajuta să folosim o unealtă care să ne raporteze code coverage-ul (ce procent din cod este verificat de teste). O soluție automată este [coverage.py](https://coverage.readthedocs.io/).

**Comment by ToniBiro** [comment]
Incep sa cred ca tu te-ai gandit ca o sa facem proiectul asta la MDS inainte sa ne apucam de el la GC :))

**Comment by Treefold** [comment]
Testarea trebuie sa respecte testing planul pentru backend

**Comment by Treefold** [comment]
Tests add in https://github.com/ToniBiro/Interseco/commit/58a3389d7b86bf228d7034b8dccc4e67ac871e7f
