### ISSUE TITLE
Culori și etichete poligoane

### ISSUE THREAD

**Issue by GabrielMajeri** [ToniBiro/Interseco#25]
Diferitele poligoane ar trebui colorate diferit pentru a le putea distinge. De asemenea, în lista de poligoane vreau să pot să pun etichete text pentru fiecare poligon (exemplu: „pătrat1”, „polygon1234”).

**Comment by Treefold** [comment]
Culorile poligoanelor ar trebui sa fie unice 
La crearea unui nou poligon acesta va primi o culoare aleatoare (care este unica printre celelate), aceasta poate fi modificata ulterior

**Comment by GabrielMajeri** [comment]
Avem culori începând cu d86ebf8b98354c66b57d023e605635c894da2fd0
