### ISSUE TITLE
Testare front end cu Selenium

### ISSUE THREAD

**Issue by GabrielMajeri** [ToniBiro/Interseco#8]
Selenium este o bibliotecă populară care îți dă posibilitatea să controlezi o instanță de browser folosind cod Python.

În acel browser poți să deschizi pagina și să interacționezi cu interfața aplicației, de parcă ai fi un utilizator real.

## Resurse

- [Getting Started with Selenium for Automated Website Testing](https://wiki.saucelabs.com/display/DOCS/Getting+Started+with+Selenium+for+Automated+Website+Testing)

- [Site-ul oficial](https://www.selenium.dev/) al proiectului

- [Documentația](https://www.selenium.dev/documentation/en/) API-ului de Python

**Comment by Treefold** [comment]
TODO: testing plan

**Comment by GabrielMajeri** [comment]
Am adăugat suport pentru testare cu [Cypress](https://www.cypress.io/) în f54149f28b037e8874c301ee4773b7dba3466ba9
